### ISSUE TITLE
Document Types that are attached to Checklists with account with a Insite Status of Closed are appearing as Technical Exceptions

### ISSUE THREAD

**Issue by rwieseler** [Cllyde/iDoc#25]

**Comment by rwieseler** [comment]
Matt Houchin is currently working on this issue.

**Comment by Cllyde** [comment]
@matthouchin, do you see the changes in this repository?

**Comment by Cllyde** [comment]
We added a button in iDoc in the settings page, that allows the iDoc user to update the Relationship records in the iDoc database with the closed or active status from Insite.
