### ISSUE TITLE
iDoc Scanning Client not recognizing BarCodes

### ISSUE THREAD

**Issue by rwieseler** [Cllyde/iDoc#26]
Nathon is currently working on this issue.  He has contacted the vendor for the Bar Code Library that we are using and is making changes.  The current iDoc Listner Service has can correctly identify bar codes that the iDoc Client can not.

**Comment by Cllyde** [comment]
@nathanhillyer

**Comment by Cllyde** [comment]
We changed the library to the same Dosadi EZTwain library that iDocListener uses, and it is picking up barcodes a lot better now.
