### ISSUE TITLE
Renewal Checklist Error

### ISSUE THREAD

**Issue by rwieseler** [Cllyde/iDoc#31]
## Server Error in '/Iportal' Application.

Object reference not set to an instance of an object. 
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.  

Stack Trace: 

[NullReferenceException: Object reference not set to an instance of an object.]
   ASI.iDoc.Data.Histories.ChecklistDocumentLinked(IDocEntity Entity, db_History Event) +36
   ASI.iDoc.Data.Histories.LogEvent(UserEvents UserEvent, IDocEntity Entity) +406
   ASI.iDoc.Data.Checklists.RefreshCIFDocuments(db_Checklist checklist) +1586
   ASI.iDoc.BaseControls.ChecklistDetails.LoadChecklist(db_Checklist CurrentChecklist, Boolean IsInitialLoad) +226
   ASI.iDoc.BaseControls.RenewChecklist.btnChecklistRenewFinished_Click(Object sender, EventArgs e) +188
   System.Web.UI.WebControls.Button.OnClick(EventArgs e) +114
   System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument) +139
   System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument) +28
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +2980

**Comment by Cllyde** [comment]
In RefreshCifDocuments, I was calling ChecklistDocumentLinked and sending a db_DocumentType, instead of the db_ChecklistLink it was expecting.
