### ISSUE TITLE
RenewChecklist not working right.

### ISSUE THREAD

**Issue by Cllyde** [Cllyde/iDoc#35]
Bank is having issues with RenewChecklist

"It doesn't display anything, and it creates the checklist- but only brings over the first document that you check."

It doesn't display anything: Could mean that no documents are showing up on the ChecklistRenew page. A Document will only show up on that page if it does not have a CIF number. Photo ID and Signature doctypes will never show up on the page, because they are automatically imported. They can still click the "renew checklist" button if there are no DocTypes displayed and it will renew the checklist with the DocTypes that weren't on the renew checklist list, but were set up be automatically imported.

Only brings over the first document that you check: I could not reproduce this behavior. Every DocType that I checked would appear on the renewed checklist.

**Comment by Cllyde** [comment]
@RWieseler Having a few screenshots would help with finding out what is actually happening.
- Checklist details showing DocTypes before clicking Renew Checklist link
- Renew Checklist screen showing DocTypes before clicking Renew Checklist button.
- Checklist details page showing the DocTypes on the newly created checklist.

**Comment by rwieseler** [comment]
I installed the latest release and renewed a checklist.  After Clicking Renewal the screen did not close.  It did create the checklist.  I will log on to Bennington and try to renew a Checklist.

**Comment by Cllyde** [comment]
I just tried to duplicate it again, and I don't think the screen is supposed to close. It shows the new checklist in the same window.
