### ISSUE TITLE
Checklist Explorer Delivering Document Types is Slow

### ISSUE THREAD

**Issue by rwieseler** [Cllyde/iDoc#38]
Bennington has many Document Types attached to their Checklist.  The performance of the displaying of the checklist has diminished due to the linking calls being made in the new release.

**Comment by Cllyde** [comment]
![image](https://f.cloud.github.com/assets/2433504/710531/4cf9d2b0-de7d-11e2-92a1-d502d465ebbd.png)
Clicking a "Documents" link from here triggers the "RefreshCIFDocuments" method to run.

![image](https://f.cloud.github.com/assets/2433504/710543/8035882c-de7d-11e2-91d2-53fd55447f30.png)
Once the page gets to this point, the Document Types summary is being loaded through an asynchronous call to the DocumentTypeHandler, which uses a view and stored procedure from the idoc database to retrieve the data.

**Comment by Cllyde** [comment]
I'm getting a 300-400 ms improvement in loading doc types by moving some of the logic that was in iDoc into the database stored procedure.
