### ISSUE TITLE
iDoc to Document Image Conversion

### ISSUE THREAD

**Issue by rwieseler** [Cllyde/iDoc#39]
Much like the Shadow Copy on an individual basics we need to create a conversion process that will push over all Signatures and Photo ID's into Document Image.

**Comment by Cllyde** [comment]
@matthouchin Is Document Image part of insite? I can't find any project for it in Vault.

**Comment by matthouchin** [comment]
I Don't know I think it is doc imaging is a project in insite I think it is under one of the util or .net projects in the Synergy tab of vault I would look there to start, it might be under real time interfaces but I don't think so.
