### ISSUE TITLE
Checklist Explorer nolonger displays in Red invalid Insite Accounts.

### ISSUE THREAD

**Issue by rwieseler** [Cllyde/iDoc#51]
Currenlty Checklist Explorer displays the Account number from the Relationship Table not the Checklist table.

**Comment by Cllyde** [comment]
Change "Documents" to "View". Change "Checklist Type" to "Category". determine if checklist has rel by if account type is null

**Comment by Cllyde** [comment]
ChecklistExplorer, AuditChecklist, and ChecklistManagement now show the account number from the checklist record in red if the checklist does not have an associated relationship record to get the account number from.
