### ISSUE TITLE
Renewal Checklist is not working.

### ISSUE THREAD

**Issue by rwieseler** [Cllyde/iDoc#53]

**Comment by Cllyde** [comment]
I've reworked how Checklist renewal works in the code. It should work exactly the same for the user though.

Creates a new checklist with the new name, IsTemplate=False, created and modified date set to "now", created by set to current user, and copies the category, account, status and restricted status from the old checklist.

If they select "Import Relationships", for every relationship on the old checklist, a new relationship is created for the new checklist with the same account number, type, primary status, shortname, and account status. last updated is set to null, and "found last updated"(not sure what this is used for) is set to false.
Then, for every relationship CIF tied to those old relationships, it creates a new relationship CIF that is tied to the new relationship created. The new relationship CIFs have the same CIF and Primary status as the old ones.

After that, it checks the renewal items that were shown to the user for whether to import the document and images.
If they pick import document, but not images, a copy of the base document type is created and linked to the new checklist.
If they pick import document and images, a checklist link is created between the old document type and the new checklist.
If they uncheck import document, the document is skipped.

Then it creates checklist links for the photo id, signature doc types and doc types with link types from the old checklist to link them to the new checklist.
