### ISSUE TITLE
Doc Type view for Linked Checklist is not working

### ISSUE THREAD

**Issue by rwieseler** [Cllyde/iDoc#54]
The Checklist Link on the Document Type some time works other time it does not.  When it doesn't work it will display.

http://ip/Iportal/DesktopModules/ASI.iDoc/Pages/ChecklistView.aspx?cl=%c2%b0%c2%ad%c2%b4%c2%b8%c2%b0%c2%b2%c2%b5%c2%b4%c3%a2%c2%b4%c2%ac%c2%b9%c3%a0%c2%b3%c2%b9%c2%ac%c2%b5%c2%b8%c3%a2%c3%a2%c2%ac%c3%a3%c2%b4%c2%b6%c2%b8%c2%ac%c2%b3%c2%b4%c3%a4%c2%b3%c2%b6%c3%a2%c2%b3%c2%b6%c2%b9%c2%b2%c2%b1%c2%b5

**Comment by Cllyde** [comment]
I'm trying to reproduce this error by choosing a checklist in checklist explorer, then clicking on one of the checklists listed in the "Linked Checklists" area. Is this the place they are having problems?

**Comment by Cllyde** [comment]
That query string after the ? decodes to "1,591345c5-8a28-49cc-b579-25e27c278304" which looks right for what the new window uses to load the checklist. I can't get this error to show up on my end. I wonder if there is any error code or message associated with this occurring?
