### ISSUE TITLE
Print Cover Sheet error

### ISSUE THREAD

**Issue by rwieseler** [Cllyde/iDoc#57]
Print Cover Sheet from the Checklist produced a PDFfile.  Print Cover Sheet from the Document Type does not produce a PDF File.

**Comment by Cllyde** [comment]
Are they getting an actual error? Or is this more of an enhancement request, because they don't like the way the coversheet looks?

**Comment by Cllyde** [comment]
I'm going to try and change this to work similar to the Print Barcodes link for the checklist.
