### ISSUE TITLE
Checklist Explorer and Document Type Search are not matching the same Doc Types

### ISSUE THREAD

**Issue by rwieseler** [Cllyde/iDoc#61]
Check list name: 
    MCCALL MARY L RE - S DONMEYER RD SALINA, KS (S/2 NE/4 34:14S:1W)
Account no: 5135011610
McCall Mary- check list – not bound yet 
McCall Mary – check list no 100036967
Shay went into this file, and saw that the $5,000.00 mortgage was missing.  She thought that it has missed being scanned since it didn’t show up. She re-added the mortgage doc type today.

When she went to link the documents the $5,000.00 mortgage showed up - but it didn’t appear to link it- but by the doc search you can see it did. (first file)

If I do a document search then it shows up in all of the correct checklists- the image is there as it should be.

.  I also notice that it shows Set date and it won’t let me edit the date

Document ID 98498

**Comment by Cllyde** [comment]
This was an issue where the DocumentDate record matching the latest DocumentTypeVersion for the DocumentType was not in the DB.
