### ISSUE TITLE
Document Type Parent CIF Level

### ISSUE THREAD

**Issue by rwieseler** [Cllyde/iDoc#65]
Drop Down option for CIF in the Application.  When this Document Type is added it will automaticlly add the CIF number to the Document Type from the Checklist.

**Comment by Cllyde** [comment]
I think we already implemented this. In Document Type Management. You can set a base doc type's link type to CIF. Whenever a document type is added to a checklist, if it has a link type that is not null, it will have it's CIF field set to the primary CIF from the checklist it was added to.

![image](https://f.cloud.github.com/assets/2433504/1099244/6e34272a-1733-11e3-8e1f-b2e3f2b68bd9.png)
