### ISSUE TITLE
Edit Document Type is Slow for Muscatine

### ISSUE THREAD

**Issue by rwieseler** [Cllyde/iDoc#80]

**Comment by Cllyde** [comment]
When adding a new document type to a checklist, the Bind to CIF logic was going through all the relationships that had a primary CIF that matched the primary CIF of the checklist the document type was added to, regardless of whether the document type needed to be linked. In the BindCif logic, I also had a loop that was causing a GetDocumentTypeByID for every relationship it found. When Muscatine had 1300+ relationships with the same primary CIF, this caused a huge slowdown, and pointed out the flaw in the logic.
I changed it to only call GetDocumentTypeByID once to get the parent doc type, so this should speed it up a lot.
